import { Buffer } from 'node:buffer';
import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';
import { stringify } from 'csv-stringify/sync';
import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from 'docx';
import { ExportFormat } from '@prisma/client';
import { cellToString, type Dataset } from './dataset.js';
import { badRequest } from '../../lib/errors.js';

export interface GeneratedExport {
  buffer: Buffer;
  contentType: string;
  extension: string;
  rowCount: number;
}

const isNumeric = (value: unknown): value is number =>
  typeof value === 'number' && Number.isFinite(value);

const isIsoDate = (value: unknown): value is string =>
  typeof value === 'string' && /^\d{4}-\d{2}-\d{2}(T[\d:.]+Z?)?$/.test(value);

async function toXlsx(dataset: Dataset): Promise<GeneratedExport> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = 'DataSynx';
  workbook.created = dataset.generatedAt;

  const sheet = workbook.addWorksheet('Dataset');
  sheet.columns = dataset.columns.map((c) => ({ header: c, key: c, width: Math.min(40, Math.max(12, c.length + 4)) }));
  sheet.getRow(1).font = { bold: true };
  sheet.views = [{ state: 'frozen', ySplit: 1 }];

  for (const row of dataset.rows) {
    const values: Record<string, unknown> = {};
    const dateColumns: string[] = [];
    for (const column of dataset.columns) {
      const value = row[column];
      if (isIsoDate(value)) {
        values[column] = new Date(value);
        dateColumns.push(column);
      } else {
        values[column] = isNumeric(value) ? value : cellToString(value);
      }
    }
    const added = sheet.addRow(values);
    for (const column of dateColumns) {
      added.getCell(column).numFmt = 'yyyy-mm-dd';
    }
  }

  const meta = workbook.addWorksheet('Metadata');
  meta.columns = [
    { header: 'Field', key: 'field', width: 28 },
    { header: 'Value', key: 'value', width: 60 },
  ];
  meta.getRow(1).font = { bold: true };
  meta.addRows([
    { field: 'Compilation', value: dataset.compilation.name },
    { field: 'Modality', value: dataset.compilation.modality },
    { field: 'Records', value: dataset.rows.length },
    { field: 'Generated at', value: dataset.generatedAt.toISOString() },
    { field: 'Generated by', value: 'DataSynx' },
  ]);

  const buffer = Buffer.from(await workbook.xlsx.writeBuffer());
  return {
    buffer,
    contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    extension: 'xlsx',
    rowCount: dataset.rows.length,
  };
}

function toCsv(dataset: Dataset): GeneratedExport {
  const csv = stringify(
    dataset.rows.map((row) => dataset.columns.map((c) => cellToString(row[c]))),
    { header: true, columns: dataset.columns, bom: true, quoted_string: true, record_delimiter: '\r\n' },
  );
  return {
    buffer: Buffer.from(csv, 'utf8'),
    contentType: 'text/csv; charset=utf-8',
    extension: 'csv',
    rowCount: dataset.rows.length,
  };
}

function toJson(dataset: Dataset): GeneratedExport {
  const payload = {
    compilation: {
      id: dataset.compilation.id,
      name: dataset.compilation.name,
      modality: dataset.compilation.modality,
    },
    generatedAt: dataset.generatedAt.toISOString(),
    generator: 'DataSynx',
    recordCount: dataset.rows.length,
    columns: dataset.columns,
    records: dataset.rows,
  };
  return {
    buffer: Buffer.from(JSON.stringify(payload, null, 2), 'utf8'),
    contentType: 'application/json',
    extension: 'json',
    rowCount: dataset.rows.length,
  };
}

function toGeoJson(dataset: Dataset): GeneratedExport {
  if (dataset.geometries.length === 0) {
    throw badRequest('This compilation contains no spatial geometry, so GeoJSON cannot be produced');
  }
  const collection = {
    type: 'FeatureCollection' as const,
    features: dataset.geometries.map((g, index) => ({
      type: 'Feature' as const,
      id: index + 1,
      geometry: g.geometry,
      properties: g.properties,
    })),
  };
  return {
    buffer: Buffer.from(JSON.stringify(collection, null, 2), 'utf8'),
    contentType: 'application/geo+json',
    extension: 'geojson',
    rowCount: collection.features.length,
  };
}

function toTxt(dataset: Dataset): GeneratedExport {
  const lines: string[] = [
    `DataSynx — ${dataset.compilation.name}`,
    `Modality: ${dataset.compilation.modality}`,
    `Records: ${dataset.rows.length}`,
    `Generated: ${dataset.generatedAt.toISOString()}`,
    '',
    '='.repeat(72),
    '',
  ];
  dataset.rows.forEach((row, index) => {
    lines.push(`Record ${index + 1}`);
    for (const column of dataset.columns) {
      const value = cellToString(row[column]);
      if (value) lines.push(`  ${column}: ${value}`);
    }
    lines.push('');
  });
  return {
    buffer: Buffer.from(lines.join('\n'), 'utf8'),
    contentType: 'text/plain; charset=utf-8',
    extension: 'txt',
    rowCount: dataset.rows.length,
  };
}

async function toDocx(dataset: Dataset): Promise<GeneratedExport> {
  const header = new TableRow({
    tableHeader: true,
    children: dataset.columns.map(
      (c) =>
        new TableCell({
          children: [new Paragraph({ children: [new TextRun({ text: c, bold: true })] })],
        }),
    ),
  });

  const body = dataset.rows.map(
    (row) =>
      new TableRow({
        children: dataset.columns.map(
          (c) => new TableCell({ children: [new Paragraph(cellToString(row[c]))] }),
        ),
      }),
  );

  const doc = new Document({
    creator: 'DataSynx',
    title: dataset.compilation.name,
    sections: [
      {
        children: [
          new Paragraph({ text: 'DataSynx Report', heading: HeadingLevel.HEADING_1 }),
          new Paragraph({ text: dataset.compilation.name, heading: HeadingLevel.HEADING_2 }),
          new Paragraph({
            alignment: AlignmentType.LEFT,
            children: [
              new TextRun(`Modality: ${dataset.compilation.modality}`),
              new TextRun({ text: `Records: ${dataset.rows.length}`, break: 1 }),
              new TextRun({ text: `Generated: ${dataset.generatedAt.toISOString()}`, break: 1 }),
            ],
          }),
          new Paragraph(''),
          new Table({ width: { size: 100, type: WidthType.PERCENTAGE }, rows: [header, ...body] }),
        ],
      },
    ],
  });

  return {
    buffer: await Packer.toBuffer(doc),
    contentType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    extension: 'docx',
    rowCount: dataset.rows.length,
  };
}

function toPdf(dataset: Dataset): Promise<GeneratedExport> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', layout: 'landscape', margin: 36 });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('error', reject);
    doc.on('end', () =>
      resolve({
        buffer: Buffer.concat(chunks),
        contentType: 'application/pdf',
        extension: 'pdf',
        rowCount: dataset.rows.length,
      }),
    );

    doc.fontSize(20).text('DataSynx Report', { continued: false });
    doc.moveDown(0.3);
    doc.fontSize(12).fillColor('#444444').text(dataset.compilation.name);
    doc
      .fontSize(9)
      .text(
        `Modality: ${dataset.compilation.modality}    Records: ${dataset.rows.length}    Generated: ${dataset.generatedAt.toISOString()}`,
      );
    doc.moveDown(0.8).fillColor('#000000');

    const columns = dataset.columns.slice(0, 8);
    const usable = doc.page.width - doc.page.margins.left - doc.page.margins.right;
    const colWidth = usable / Math.max(columns.length, 1);
    const lineHeight = 14;

    const drawHeader = () => {
      doc.fontSize(8).font('Helvetica-Bold');
      columns.forEach((c, i) => {
        doc.text(c, doc.page.margins.left + i * colWidth, doc.y, { width: colWidth - 4, ellipsis: true });
        if (i < columns.length - 1) doc.moveUp();
      });
      doc.moveDown(0.4);
      doc
        .moveTo(doc.page.margins.left, doc.y)
        .lineTo(doc.page.width - doc.page.margins.right, doc.y)
        .strokeColor('#999999')
        .stroke();
      doc.moveDown(0.3);
      doc.font('Helvetica');
    };

    drawHeader();

    for (const row of dataset.rows) {
      if (doc.y > doc.page.height - doc.page.margins.bottom - lineHeight * 2) {
        doc.addPage();
        drawHeader();
      }
      const y = doc.y;
      columns.forEach((c, i) => {
        doc.fontSize(8).text(cellToString(row[c]).slice(0, 120), doc.page.margins.left + i * colWidth, y, {
          width: colWidth - 4,
          height: lineHeight,
          ellipsis: true,
        });
      });
      doc.y = y + lineHeight;
    }

    if (dataset.rows.length === 0) doc.fontSize(10).text('No records in this compilation.');
    if (dataset.columns.length > columns.length) {
      doc.moveDown(1);
      doc
        .fontSize(8)
        .fillColor('#666666')
        .text(
          `Showing ${columns.length} of ${dataset.columns.length} columns. Use XLSX or CSV for the complete dataset.`,
        );
    }

    doc.end();
  });
}

export async function generateExport(format: ExportFormat, dataset: Dataset): Promise<GeneratedExport> {
  switch (format) {
    case ExportFormat.XLSX:
      return toXlsx(dataset);
    case ExportFormat.CSV:
      return Promise.resolve(toCsv(dataset));
    case ExportFormat.JSON:
      return Promise.resolve(toJson(dataset));
    case ExportFormat.GEOJSON:
      return Promise.resolve(toGeoJson(dataset));
    case ExportFormat.TXT:
      return Promise.resolve(toTxt(dataset));
    case ExportFormat.DOCX:
      return toDocx(dataset);
    case ExportFormat.PDF:
      return toPdf(dataset);
    default:
      throw badRequest(`Unsupported export format: ${format}`);
  }
}
